#!/usr/bin/env bash
# prints Best School as long as condition is true
counter=1
text='Best School'
while [[ counter -le 10 ]]
do
	if [[ counter -eq 9 ]]
	then
		echo -e "Best School\nHi"
	else	
		echo "${text}"
	fi
	((counter++))
done
