#!/usr/bin/env bash
# prints using while loop
counter=1
text='Best School'
while [[ $counter -le 10 ]]
do
	if [[ $counter -eq 4 ]]
	then
		echo "bad luck"
	elif [[ $counter -eq 8 ]]
	then
		echo "good luck"
	else
		echo "${text}"
	fi
	((counter++))
done
